#############################################################################
# Makefile for building: qpyconsole
# Generated by qmake (2.00a) (Qt 4.1.1) on: Fri Mar 24 09:06:20 2006
# Project:  qpyconsole.pro
# Template: app
# Command: /opt0/lib/qt-4.1.1-64/bin/qmake -unix -o Makefile qpyconsole.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
LEX           = flex
YACC          = yacc
DEFINES       = -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT  $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT  $(DEFINES)
LEXFLAGS      = 
YACCFLAGS     = -d
INCPATH       = -I/opt0/lib/qt-4.1.1-64/mkspecs/linux-g++-64 -I. -I/opt0/lib/qt-4.1.1-64/include/QtCore -I/opt0/lib/qt-4.1.1-64/include/QtGui -I/opt0/lib/qt-4.1.1-64/include/Qt3Support -I/opt0/lib/qt-4.1.1-64/include -I. -Iinclude -I$(PYTHON_PATH)/include/python$(PYTHON_VERSION) -I.moc -I.ui
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/opt0/lib/qt-4.1.1-64/lib
LIBS          = $(SUBLIBS)  -L/opt0/lib/qt-4.1.1-64/lib -L$(PYTHON_PATH)/lib/python$(PYTHON_VERSION)/config -lpython$(PYTHON_VERSION) -lutil -lQt3Support_debug -L/home/mondrian/packages/qt-x11-opensource-src-4.1.1/lib -lQtSql_debug -lQtXml_debug -L/usr/X11R6/lib64 -lQtNetwork_debug -lQtGui_debug -lpng -lSM -lICE -lXi -lXrender -lXrandr -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore_debug -lz -lm -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt0/lib/qt-4.1.1-64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/interceptor.cpp \
		src/pymain.cpp \
		src/qpyconsole.cpp \
		src/qconsole.cpp .moc/moc_interceptor.cpp \
		.moc/moc_qconsole.cpp
OBJECTS       = .obj/interceptor.o \
		.obj/pymain.o \
		.obj/qpyconsole.o \
		.obj/qconsole.o \
		.obj/moc_interceptor.o \
		.obj/moc_qconsole.o
DIST          = /opt0/lib/qt-4.1.1-64/mkspecs/qconfig.pri \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/qt_config.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/exclusive_builds.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/default_pre.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/debug.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/default_post.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/warn_on.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/qt.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/unix/thread.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/moc.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/resources.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/uic.prf \
		qpyconsole.pro
QMAKE_TARGET  = qpyconsole
DESTDIR       = 
TARGET        = qpyconsole

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qpyconsole.pro  /opt0/lib/qt-4.1.1-64/mkspecs/linux-g++-64/qmake.conf /opt0/lib/qt-4.1.1-64/mkspecs/qconfig.pri \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/qt_config.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/exclusive_builds.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/default_pre.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/debug.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/default_post.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/warn_on.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/qt.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/unix/thread.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/moc.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/resources.prf \
		/opt0/lib/qt-4.1.1-64/mkspecs/features/uic.prf \
		/opt0/lib/qt-4.1.1-64/lib/libQt3Support_debug.prl \
		/opt0/lib/qt-4.1.1-64/lib/libQtSql_debug.prl \
		/opt0/lib/qt-4.1.1-64/lib/libQtCore_debug.prl \
		/opt0/lib/qt-4.1.1-64/lib/libQtXml_debug.prl \
		/opt0/lib/qt-4.1.1-64/lib/libQtGui_debug.prl \
		/opt0/lib/qt-4.1.1-64/lib/libQtNetwork_debug.prl
	$(QMAKE) -unix -o Makefile qpyconsole.pro
/opt0/lib/qt-4.1.1-64/mkspecs/qconfig.pri:
/opt0/lib/qt-4.1.1-64/mkspecs/features/qt_config.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/exclusive_builds.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/default_pre.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/debug.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/default_post.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/warn_on.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/qt.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/unix/thread.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/moc.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/resources.prf:
/opt0/lib/qt-4.1.1-64/mkspecs/features/uic.prf:
/opt0/lib/qt-4.1.1-64/lib/libQt3Support_debug.prl:
/opt0/lib/qt-4.1.1-64/lib/libQtSql_debug.prl:
/opt0/lib/qt-4.1.1-64/lib/libQtCore_debug.prl:
/opt0/lib/qt-4.1.1-64/lib/libQtXml_debug.prl:
/opt0/lib/qt-4.1.1-64/lib/libQtGui_debug.prl:
/opt0/lib/qt-4.1.1-64/lib/libQtNetwork_debug.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qpyconsole.pro

dist: 
	@$(CHK_DIR_EXISTS) ".obj/qpyconsole1.0.0" || $(MKDIR) ".obj/qpyconsole1.0.0"
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/qpyconsole1.0.0/ && $(COPY_FILE) --parents include/interceptor.h include/qpyconsole.h include/qconsole.h .obj/qpyconsole1.0.0/ && $(COPY_FILE) --parents src/interceptor.cpp src/pymain.cpp src/qpyconsole.cpp src/qconsole.cpp .obj/qpyconsole1.0.0/ && (cd `dirname .obj/qpyconsole1.0.0` && $(TAR) qpyconsole1.0.0.tar qpyconsole1.0.0 && $(COMPRESS) qpyconsole1.0.0.tar) && $(MOVE) `dirname .obj/qpyconsole1.0.0`/qpyconsole1.0.0.tar.gz . && $(DEL_FILE) -r .obj/qpyconsole1.0.0


yaccclean:
lexclean:
clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/opt0/lib/qt-4.1.1-64/bin/moc:
	(cd "$(QTDIR)/src/tools/moc" && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_interceptor.cpp .moc/moc_qconsole.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_interceptor.cpp .moc/moc_qconsole.cpp
.moc/moc_interceptor.cpp: include/interceptor.h \
		/opt0/lib/qt-4.1.1-64/bin/moc
	/opt0/lib/qt-4.1.1-64/bin/moc $(DEFINES) $(INCPATH) include/interceptor.h -o .moc/moc_interceptor.cpp

.moc/moc_qconsole.cpp: include/interceptor.h \
		include/qconsole.h \
		/opt0/lib/qt-4.1.1-64/bin/moc
	/opt0/lib/qt-4.1.1-64/bin/moc $(DEFINES) $(INCPATH) include/qconsole.h -o .moc/moc_qconsole.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all:
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_image_collection_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

.obj/interceptor.o: src/interceptor.cpp include/interceptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/interceptor.o src/interceptor.cpp

.obj/pymain.o: src/pymain.cpp include/qpyconsole.h \
		include/qconsole.h \
		include/interceptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/pymain.o src/pymain.cpp

.obj/qpyconsole.o: src/qpyconsole.cpp include/qpyconsole.h \
		include/qconsole.h \
		include/interceptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qpyconsole.o src/qpyconsole.cpp

.obj/qconsole.o: src/qconsole.cpp include/qconsole.h \
		include/interceptor.h \
		include/q3richtext_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qconsole.o src/qconsole.cpp

.obj/moc_interceptor.o: .moc/moc_interceptor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_interceptor.o .moc/moc_interceptor.cpp

.obj/moc_qconsole.o: .moc/moc_qconsole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_qconsole.o .moc/moc_qconsole.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

